#%RAML 1.0 register client example
client_name:	Example App
client_uri:	http://client.example.com
scope: photos
redirect_uri:	[http://client.example.com/home]
grant_types:	[authorization_code, password]
response_types: [code]
token_endpoint_auth_method:	client_secret_basic
