#%RAML 1.0 Token Requests by Grant Type
PasswordGrant:
  grant_type: password
  username: Joe Bloggs
  password: secret
  scope: photos

AuthCodeGrant:
  grant_type: code
  code: SplxlOBeZQQYbYS6WxSbIA
  redirect_uri: http://client.example.com/
  client_id: ttwCD9hb4OckmcGDnmC3J3Jr

RefreshTokenGrant:
  grant_type: refresh_token
  refresh_token: tGzv3JOkF0XG5Qx2TlKWIA
