#%RAML 1.0 securitySchemes
basic:
  type: Basic Authentication
  displayName: Basic Authentication (client credentials)
  description: |
    This API supports Basic Authentication using client ID and client secret as username and password credentials.

oauth_2_0:
  type: OAuth 2.0
  displayName: OAuth 2.0 Authentication
  description: |
    OAuth 2.0 for authenticating NMOS API requests.
  describedBy:
    headers:
      Authorization:
        description: |
           Used to send a valid OAuth 2 access token. Do not use
           with the "access_token" query string parameter.
        type: string
    queryParameters:
      access_token:
        description: |
           Used to send a valid OAuth 2 access token. Do not use with
           the "Authorization" header.
        type: string
    responses:
      401:
        description: |
            Bad or expired token. This can happen if the user or owner
            revoked or expired an access token.
      403:
        description: |
            Bad OAuth request.
  settings:
    authorizationUri: http://example.api.com/x-nmos/oauth/{version}/authorize
    accessTokenUri:  http://example.api.com/x-nmos/oauth/{version}/token
    authorizationGrants: [ authorization_code, password ]
    scopes: [ photos ]
