#%RAML 1.0 Traits
Basic:
  description: Basic authentication using user's username nad password
  usage: To protect resources containing confidential client information
  headers:
    Authorization:
      displayName: Basic Authorization
      description: Colon-seperated, base-64 encoded string, of User's username and password
      type: string
      required: true

OAuthBasic:
  description: Basic authentication using Client ID and client Secret
  usage: Applied in accordance with RFC 6749
  headers:
    Authorization:
      displayName: OAuth 2.0 Basic Authorization
      description: Colon-seperated, base-64 encoded string, of Client ID and Client Secret
      type: string
      required: true

AuthorizationCodeRequest:
  queryParameters:
    response_type:
      description: Type of OAuth 2.0 response. MUST be set to "code"
      required: true
    client_id:
      description: The identifier of the client authenticating
      required: true
    redirect_uri:
      description: URI to direct resource owner's user-agent back to clients
      required: false
    scope:
      description: The scope of the access request
      required: false
    state:
      description: Value used by client to maintain state between request and callback
      required: false
