#%RAML 1.0 Types
TokenAuthorizeRequest:
  properties:
    grant_type:
      description: The OAuth 2.0 grant type of the request
      type: string
      required: true
    code:
      description:  The authorization code received from the authorization server
      type: string
      required: true
    redirect_uri:
      description: Absolute URI used by the auth server to redirect the user-agent, previously established during client registration
      type: string
    client_id:
      description: The identifier of the client authenticating
      type: string

TokenPasswordRequest:
  properties:
    grant_type:
      description: The OAuth 2.0 grant type of the request
      type: string
      required: true
    username:
      description: Username for the Password Credentials Grant
      type: string
      required: true
    password:
      description: Password for the Password Credentials grant_type
      type: string
      required: true
    scope:
      description: The scope of the access request
      type: string
      required: true

TokenRefreshRequest:
  properties:
      grant_type:
        description: MUST be set to "refresh_token"
        required: true
      refresh_token:
        description: The refresh token issued to the client inside the bearer token
        required: true
      scope:
        description: The scope of the access request
        required: false

RevokeRequest:
  properties:
    access_token:
      description: The token (access / refresh) that the client wants to revoke
      required: true
    token_type_hint:
      description: A hint about the type of the token submitted for revocation
      required: true
      enum: [ access_token, refresh_token ]
